# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production

on:
  push:
    branches:
      - main
      - qa

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build
      - run: rm -rf public_html/prod/ && mkdir -p public_html/prod/ && mv build/ public_html/prod/
        if: ${{ github.ref == 'refs/heads/main' }}
      - run: rm -rf public_html/qa/ && mkdir -p public_html/qa/ && mv build/ public_html/qa/
        if: ${{ github.ref == 'refs/heads/qa' }}
 
